<?php
include_once 'Circle.php';

class Cylinder extends Circle
{
    public $height;

    public function __construct($radius, $color, $height)
    {
        parent::__construct($radius, $color);
        $this->height = $height;
    }

    /**
     * @return mixed
     */
    public function getHeight()
    {
        return $this->height;
    }

    /**
     * @param mixed $height
     */
    public function setHeight($height)
    {
        $this->height = $height;
    }

    public function getArea()
    {
        return parent::getArea(); // TODO: Change the autogenerated stub
    }

    public function getVolume()
    {
        return parent::getArea() * $this->height;
    }

}